# import pickle
# pickle.dump(5, open(f'output/MIDI/xd', "wb"))

# import tensorflow as tf
# print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

# import pickle as pkl
# run_id = 5
# run_id_file = "RNN_attention_multihot_encoding/run_id"
# with open(run_id_file, 'wb') as f:
#     pkl.dump(run_id, f)


# from music21 import stream, note, duration
#
# midi_stream = stream.Stream()
#
# notes = [(0, 1), (5, 0), (-1, 1), (0, 1), (5, 0), (0, 1), (5, 4)] * 100
# # create note and chord objects based on the values generated by the model
# for n in notes:
#     dur = duration.Duration(n[1])
#     if n[0] == -1:
#         midi_stream.append(note.Rest(duration=dur))
#     else:
#         midi_stream.append(note.Note(n[0], duration=dur))
#
# midi_stream.write('midi', fp='trials.mid')


# from RNN_attention_multihot_encoding.midi_utils import open_midi
# open_midi("..\\datasets\\130000_Pop_Rock_Classical_Videogame_EDM_MIDI_Archive\\1\\10000yr.mid")


# from utilities.midi_utils import translate_chord
# print(translate_chord([2, 3, 4, 5, 6, 6, 1], separator="."))

